common:
  http:
    host: "localhost"
    enabled: true
    port: 8081
    fileserver_port: 8083
  ws:
    enabled: true
    port: 8082
  log_mode: "debug"
aws:
  region: "region"
  key_id: "keyID"
  secret: "secret"
  token: ""
  bucket: ""
default_convert_library: "chromedp"
default_convert_output: "file"
file_num: 3

