common:
  http:
    host: "localhost"
    enabled: true
    port: 8081
  ws:
    enabled: true
    port: 8082
  log_mode: "debug"
file_server:
  enabled: true
  port: 8083
aws:
  region: "region"
  key_id: "keyID"
  secret: "secret"
  token: ""
  bucket: ""
default_convert_library: "chromedp"
default_convert_output: "file"
file_num: 3