common:
  http:
    enabled: true
    port: 8081
  ws:
    enabled: true
    port: 8082
  log_mode: "debug"
specific:
  aws:
    region: "region"
    key_id: "keyID"
    secret: "secret"
    token: ""
    bucket: ""
  default_convert_library: "chromedp"

